### ISSUE TITLE
aka: add option to disable certain features. 

### ISSUE THREAD

**Issue by ghost** [AwwCookies/ZNC-Modules#3]
I only care about the nicks/hosts, not channels people have been in. Someone else might only care about channels people have been in, not the nicks/hosts.

Maybe something like this?
`/msg *aka disable channels`
`/msg *aka enable channels`

`/msg *aka disable nicks`
`/msg *aka enable nicks`

**Comment by emagaliff** [comment]
@KindOne- What exactly do you want disabled? The nick/channel info are separate commands. You can simply not use commands you don't want.

**Comment by ghost** [comment]
I'll reword, I don't want it tracking channels people have been in, so don't create or write a `chans.json`.

So, I want an option to disable it.

**Comment by emagaliff** [comment]
@KindOne- Talk to @AwwCookies , I'm working on the sqlite branch.

**Comment by emagaliff** [comment]
`sqlite` is now the default, so the multiple files shouldn't be an issue. Space saving without channels is negligible at best, and nicks are also used to track channels, so there isn't really a feasible way to stop tracking them and retain the channel feature.
