### ISSUE TITLE
Errors on new, disconnected network

### ISSUE THREAD

**Issue by iynque** [AwwCookies/ZNC-Modules#8]
I added a new network to ZNC, but did not connect ZNC to the IRC server (just my client to ZNC). I was able to configure other modules that required configuring (cert, for example) before connecting for the first time. However, I could not configure aka.

When I sent `/msg *aka config NOTIFY_ON_MODERATED 1`, I received no response back. When I sent `/msg *aka getconfig`, I got back `<*aka> {}`.

Once I connected the network for the first time, my commands to aka were recognized; everything worked fine after connecting ZNC to the IRC network.

Probably an uncommon use-case and not terribly important, but is was a bit confusing 😃

Using ZNC 1.7.x-git-510-1e46ea8

**Comment by emagaliff** [comment]
@iynque What version of aka are you using? I fixed a very similar bug yesterday, and "Version 1.0.7 (Last Updated: Nov 14, 2015)" is the latest.

I tried exactly what you did, adding a new network and following your same steps (loaded aka before initial connect) and was unable to replicate it

**Comment by iynque** [comment]
@emagaliff Ah, you're right, I wasn't updated. Could have sworn I used the update command, but I was on 1.0.5. I tried again on 1.0.7 and it works correctly.

Sorry to make you test it for nothing! (and I sorry I didn't say which version like I should have 😛)
