### ISSUE TITLE
Give specific feedback on ``offenses`` commands

### ISSUE THREAD

**Issue by iynque** [AwwCookies/ZNC-Modules#9]
When using `offenses nick` and `offenses host`, it would be helpful to get more specific feedback.

Instead of the generic

```
No results found for: <nick>
No results found for: <host>
```

Return results/errors like

```
No offenses found for: <nick>
No offenses found for: <host>
```

---

> …and now, why this might matter…

---

I use the alias module to send multiple commands to aka at the same time. My alias looks like this:

```
<*alias> Actions for alias AKA:
<*alias> 0  PRIVMSG *aka :trace nick %1%
<*alias> 1  PRIVMSG *aka :trace host %?2%
<*alias> 2  PRIVMSG *aka :trace nickchans %1%
<*alias> 3  PRIVMSG *aka :offenses nick %1%
<*alias> 4  PRIVMSG *aka :offenses host %?2%
<*alias> 5  PRIVMSG *aka :seen nick %1%
<*alias> 6  PRIVMSG *aka :seen host %?2%
<*alias> 7  PRIVMSG *aka :geoip nick %1%
<*alias> 8  PRIVMSG *aka :geoip host %?2%
<*alias> End of actions for alias AKA.
```

So I can use `/aka <nick>` or `/aka <nick> <host>` and get back a lot of info from aka, like

`/aka MuffinMedic`

```
[17:54:09] <*aka> MuffinMedic was also known as: MonsterMedic, MuffinMedic (unaffiliated/muffinmedic)
[17:54:10] <*aka> MuffinMedic was found in: #znc #znc-dev
[17:54:11] <*aka> No results found for: MuffinMedic
[17:54:12] <*aka> MuffinMedic was last seen in #znc at 2015-11-10 02:12:49.492054 saying "fi... Finland?"
[17:54:13] <*aka> Invalid host for geolocation (unaffiliated/muffinmedic)
```

Every line tells me what the information is, except the line returned from `offenses nick MuffinMedic`. The output would be moderately improved if, instead of `No results found for: MuffinMedic` it included a hint at which command this line corresponds to, specifically, `No offenses found for: MuffinMedic`.

**Comment by emagaliff** [comment]
@iynque I like your multiple commands idea for alias, so I added an `all` command in b60f9ad (1.0.8). See [README](https://github.com/AwwCookies/ZNC-Modules/blob/master/Aka/README.md) for specifics and `update` as usual.
